export const languageTypes = {
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE"
}

export const authTypes = {
    SIGNIN: 'SIGNIN',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGN_OUT: 'SIGN_OUT',
    SIGNUP: 'SIGNUP',
    FORGOTPASS: 'FORGOTPASS',
}

export const appTypes = {
    SET_SEARCH_TERM: 'SET_SEARCH_TERM',
    SET_STICKY: 'SET_STICKY',
    REMOVE_STICKY: 'REMOVE_STICKY',
    SET_SIDEBAR_STICKY: 'SET_SIDEBAR_STICKY',
    REMOVE_SIDEBAR_STICKY: 'REMOVE_SIDEBAR_STICKY',
    TOGGLE_DRAWER: 'TOGGLE_DRAWER',
    TOGGLE_MODAL: 'TOGGLE_MODAL',
}

export const cartTypes = {
    REHYDRATE: 'REHYDRATE',
    TOGGLE_CART: 'TOGGLE_CART',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    CLEAR_CART: 'CLEAR_CART',
    APPLY_COUPON: 'APPLY_COUPON',
    REMOVE_COUPON: 'REMOVE_COUPON',
    TOGGLE_RESTAURANT: 'TOGGLE_RESTAURANT',
}

export const profileTypes = {
    HANDLE_ON_INPUT_CHANGE: 'HANDLE_ON_INPUT_CHANGE',
    ADD_OR_UPDATE_ADDRESS: 'ADD_OR_UPDATE_ADDRESS',
    DELETE_ADDRESS: 'DELETE_ADDRESS',
    ADD_CARD: 'ADD_CARD',
    DELETE_CARD: 'DELETE_CARD',
    SET_PRIMARY_CONTACT: 'SET_PRIMARY_CONTACT',
    SET_PRIMARY_ADDRESS: 'SET_PRIMARY_ADDRESS',
    SET_PRIMARY_SCHEDULE: 'SET_PRIMARY_SCHEDULE',
    SET_PRIMARY_CARD: 'SET_PRIMARY_CARD',
}